/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceSimRouteImport } from './routes/voice-sim'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as ApiPublicSimTickRouteImport } from './routes/api/public/sim-tick'
import { Route as ApiPublicAiProxyRouteImport } from './routes/api/public/ai-proxy'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as ApiPublicCopilotSetsRouteImport } from './routes/api/public/copilot/sets'
import { Route as ApiPublicCopilotModelRouteImport } from './routes/api/public/copilot/model'
import { Route as ApiPublicCopilotFanBrainRouteImport } from './routes/api/public/copilot/fan-brain'
import { Route as AuthenticatedAdminAdminSetsRouteImport } from './routes/_authenticated/_admin/admin.sets'
import { Route as AuthenticatedAdminAdminApiKeysRouteImport } from './routes/_authenticated/_admin/admin.api-keys'
import { Route as AuthenticatedAdminAdminModelsIndexRouteImport } from './routes/_authenticated/_admin/admin.models.index'
import { Route as AuthenticatedAdminAdminModelsIdRouteImport } from './routes/_authenticated/_admin/admin.models.$id'

const VoiceSimRoute = VoiceSimRouteImport.update({
  id: '/voice-sim',
  path: '/voice-sim',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicSimTickRoute = ApiPublicSimTickRouteImport.update({
  id: '/api/public/sim-tick',
  path: '/api/public/sim-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiProxyRoute = ApiPublicAiProxyRouteImport.update({
  id: '/api/public/ai-proxy',
  path: '/api/public/ai-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const ApiPublicCopilotSetsRoute = ApiPublicCopilotSetsRouteImport.update({
  id: '/api/public/copilot/sets',
  path: '/api/public/copilot/sets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCopilotModelRoute = ApiPublicCopilotModelRouteImport.update({
  id: '/api/public/copilot/model',
  path: '/api/public/copilot/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCopilotFanBrainRoute =
  ApiPublicCopilotFanBrainRouteImport.update({
    id: '/api/public/copilot/fan-brain',
    path: '/api/public/copilot/fan-brain',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAdminSetsRoute =
  AuthenticatedAdminAdminSetsRouteImport.update({
    id: '/sets',
    path: '/sets',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminApiKeysRoute =
  AuthenticatedAdminAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminModelsIndexRoute =
  AuthenticatedAdminAdminModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminModelsIdRoute =
  AuthenticatedAdminAdminModelsIdRouteImport.update({
    id: '/models/$id',
    path: '/models/$id',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRoute
  '/login': typeof LoginRoute
  '/voice-sim': typeof VoiceSimRoute
  '/app': typeof AuthenticatedAppRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/api/public/ai-proxy': typeof ApiPublicAiProxyRoute
  '/api/public/sim-tick': typeof ApiPublicSimTickRoute
  '/admin/api-keys': typeof AuthenticatedAdminAdminApiKeysRoute
  '/admin/sets': typeof AuthenticatedAdminAdminSetsRoute
  '/api/public/copilot/fan-brain': typeof ApiPublicCopilotFanBrainRoute
  '/api/public/copilot/model': typeof ApiPublicCopilotModelRoute
  '/api/public/copilot/sets': typeof ApiPublicCopilotSetsRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/models/$id': typeof AuthenticatedAdminAdminModelsIdRoute
  '/admin/models/': typeof AuthenticatedAdminAdminModelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRoute
  '/login': typeof LoginRoute
  '/voice-sim': typeof VoiceSimRoute
  '/app': typeof AuthenticatedAppRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/public/ai-proxy': typeof ApiPublicAiProxyRoute
  '/api/public/sim-tick': typeof ApiPublicSimTickRoute
  '/admin/api-keys': typeof AuthenticatedAdminAdminApiKeysRoute
  '/admin/sets': typeof AuthenticatedAdminAdminSetsRoute
  '/api/public/copilot/fan-brain': typeof ApiPublicCopilotFanBrainRoute
  '/api/public/copilot/model': typeof ApiPublicCopilotModelRoute
  '/api/public/copilot/sets': typeof ApiPublicCopilotSetsRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/models/$id': typeof AuthenticatedAdminAdminModelsIdRoute
  '/admin/models': typeof AuthenticatedAdminAdminModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/extension': typeof ExtensionRoute
  '/login': typeof LoginRoute
  '/voice-sim': typeof VoiceSimRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/api/public/ai-proxy': typeof ApiPublicAiProxyRoute
  '/api/public/sim-tick': typeof ApiPublicSimTickRoute
  '/_authenticated/_admin/admin/api-keys': typeof AuthenticatedAdminAdminApiKeysRoute
  '/_authenticated/_admin/admin/sets': typeof AuthenticatedAdminAdminSetsRoute
  '/api/public/copilot/fan-brain': typeof ApiPublicCopilotFanBrainRoute
  '/api/public/copilot/model': typeof ApiPublicCopilotModelRoute
  '/api/public/copilot/sets': typeof ApiPublicCopilotSetsRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_admin/admin/models/$id': typeof AuthenticatedAdminAdminModelsIdRoute
  '/_authenticated/_admin/admin/models/': typeof AuthenticatedAdminAdminModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extension'
    | '/login'
    | '/voice-sim'
    | '/app'
    | '/admin/login'
    | '/admin'
    | '/api/public/ai-proxy'
    | '/api/public/sim-tick'
    | '/admin/api-keys'
    | '/admin/sets'
    | '/api/public/copilot/fan-brain'
    | '/api/public/copilot/model'
    | '/api/public/copilot/sets'
    | '/admin/'
    | '/admin/models/$id'
    | '/admin/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extension'
    | '/login'
    | '/voice-sim'
    | '/app'
    | '/admin/login'
    | '/api/public/ai-proxy'
    | '/api/public/sim-tick'
    | '/admin/api-keys'
    | '/admin/sets'
    | '/api/public/copilot/fan-brain'
    | '/api/public/copilot/model'
    | '/api/public/copilot/sets'
    | '/admin'
    | '/admin/models/$id'
    | '/admin/models'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/extension'
    | '/login'
    | '/voice-sim'
    | '/_authenticated/_admin'
    | '/_authenticated/app'
    | '/admin/login'
    | '/_authenticated/_admin/admin'
    | '/api/public/ai-proxy'
    | '/api/public/sim-tick'
    | '/_authenticated/_admin/admin/api-keys'
    | '/_authenticated/_admin/admin/sets'
    | '/api/public/copilot/fan-brain'
    | '/api/public/copilot/model'
    | '/api/public/copilot/sets'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_admin/admin/models/$id'
    | '/_authenticated/_admin/admin/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ExtensionRoute: typeof ExtensionRoute
  LoginRoute: typeof LoginRoute
  VoiceSimRoute: typeof VoiceSimRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPublicAiProxyRoute: typeof ApiPublicAiProxyRoute
  ApiPublicSimTickRoute: typeof ApiPublicSimTickRoute
  ApiPublicCopilotFanBrainRoute: typeof ApiPublicCopilotFanBrainRoute
  ApiPublicCopilotModelRoute: typeof ApiPublicCopilotModelRoute
  ApiPublicCopilotSetsRoute: typeof ApiPublicCopilotSetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-sim': {
      id: '/voice-sim'
      path: '/voice-sim'
      fullPath: '/voice-sim'
      preLoaderRoute: typeof VoiceSimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/sim-tick': {
      id: '/api/public/sim-tick'
      path: '/api/public/sim-tick'
      fullPath: '/api/public/sim-tick'
      preLoaderRoute: typeof ApiPublicSimTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-proxy': {
      id: '/api/public/ai-proxy'
      path: '/api/public/ai-proxy'
      fullPath: '/api/public/ai-proxy'
      preLoaderRoute: typeof ApiPublicAiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/api/public/copilot/sets': {
      id: '/api/public/copilot/sets'
      path: '/api/public/copilot/sets'
      fullPath: '/api/public/copilot/sets'
      preLoaderRoute: typeof ApiPublicCopilotSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/copilot/model': {
      id: '/api/public/copilot/model'
      path: '/api/public/copilot/model'
      fullPath: '/api/public/copilot/model'
      preLoaderRoute: typeof ApiPublicCopilotModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/copilot/fan-brain': {
      id: '/api/public/copilot/fan-brain'
      path: '/api/public/copilot/fan-brain'
      fullPath: '/api/public/copilot/fan-brain'
      preLoaderRoute: typeof ApiPublicCopilotFanBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/sets': {
      id: '/_authenticated/_admin/admin/sets'
      path: '/sets'
      fullPath: '/admin/sets'
      preLoaderRoute: typeof AuthenticatedAdminAdminSetsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/api-keys': {
      id: '/_authenticated/_admin/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/models/': {
      id: '/_authenticated/_admin/admin/models/'
      path: '/models'
      fullPath: '/admin/models/'
      preLoaderRoute: typeof AuthenticatedAdminAdminModelsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/models/$id': {
      id: '/_authenticated/_admin/admin/models/$id'
      path: '/models/$id'
      fullPath: '/admin/models/$id'
      preLoaderRoute: typeof AuthenticatedAdminAdminModelsIdRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
  }
}

interface AuthenticatedAdminAdminRouteChildren {
  AuthenticatedAdminAdminApiKeysRoute: typeof AuthenticatedAdminAdminApiKeysRoute
  AuthenticatedAdminAdminSetsRoute: typeof AuthenticatedAdminAdminSetsRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
  AuthenticatedAdminAdminModelsIdRoute: typeof AuthenticatedAdminAdminModelsIdRoute
  AuthenticatedAdminAdminModelsIndexRoute: typeof AuthenticatedAdminAdminModelsIndexRoute
}

const AuthenticatedAdminAdminRouteChildren: AuthenticatedAdminAdminRouteChildren =
  {
    AuthenticatedAdminAdminApiKeysRoute: AuthenticatedAdminAdminApiKeysRoute,
    AuthenticatedAdminAdminSetsRoute: AuthenticatedAdminAdminSetsRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
    AuthenticatedAdminAdminModelsIdRoute: AuthenticatedAdminAdminModelsIdRoute,
    AuthenticatedAdminAdminModelsIndexRoute:
      AuthenticatedAdminAdminModelsIndexRoute,
  }

const AuthenticatedAdminAdminRouteWithChildren =
  AuthenticatedAdminAdminRoute._addFileChildren(
    AuthenticatedAdminAdminRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ExtensionRoute: ExtensionRoute,
  LoginRoute: LoginRoute,
  VoiceSimRoute: VoiceSimRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiPublicAiProxyRoute: ApiPublicAiProxyRoute,
  ApiPublicSimTickRoute: ApiPublicSimTickRoute,
  ApiPublicCopilotFanBrainRoute: ApiPublicCopilotFanBrainRoute,
  ApiPublicCopilotModelRoute: ApiPublicCopilotModelRoute,
  ApiPublicCopilotSetsRoute: ApiPublicCopilotSetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
